### ISSUE TITLE
phys2bids not working for multifrequency files

### ISSUE THREAD

**Issue by vinferrer** [physiopy/phys2bids#163]
## Expected Behavior
`` phys2bids -in Test_belt_pulse_multifreq.txt -chtrig 3 ``
expecting the program to run to the end and generate the png files and the tgv file

## Actual Behavior
```
phys2bids -in Test_belt_pulse_multifreq.txt -chtrig 3
INFO:phys2bids.phys2bids:Currently running phys2bids version v1.3.0-beta+136.g76b51b2
INFO:phys2bids.phys2bids:Input file is Test_belt_pulse_multifreq.txt
INFO:phys2bids.utils:File extension is .txt
WARNING:phys2bids.utils:If both acq and txt files exist in the path, acq will be selected.
INFO:phys2bids.phys2bids:Reading the file ./Test_belt_pulse_multifreq.txt
INFO:phys2bids.interfaces.txt:phys2bids detected that your file is in AcqKnowledge format
WARNING:phys2bids.interfaces.txt:Interval is not in seconds. Converting its value.
INFO:phys2bids.phys2bids:Reading infos
INFO:phys2bids.physio_obj:
------------------------------------------------
File Test_belt_pulse_multifreq.txt contains:
01. RESP - RSP100C; sampled at 10000.0 Hz
02. PULSE - Custom, DA100C; sampled at 625.0 Hz
03. MR TRIGGER - Custom, HLT100C - A 5; sampled at 10000.0 Hz
04. PPG100C; sampled at 10000.0 Hz
05. CO2; sampled at 10000.0 Hz
------------------------------------------------

INFO:phys2bids.physio_obj:Counting trigger points
WARNING:phys2bids.physio_obj:The necessary options to find the amount of timepoints were not provided.
INFO:phys2bids.phys2bids:Plot trigger
WARNING:phys2bids.phys2bids:Found 2 different frequencies in input!
INFO:phys2bids.phys2bids:Preparing 2 output files.
Traceback (most recent call last):
  File "/home/vicente/.local/bin/phys2bids", line 11, in <module>
    load_entry_point('phys2bids', 'console_scripts', 'phys2bids')()
  File "/home/vicente/phys2bids/phys2bids/phys2bids.py", line 305, in _main
    phys_out[uniq_freq].delete_at_index(phys_in.ch_amount - i - 1)
  File "/home/vicente/phys2bids/phys2bids/physio_obj.py", line 230, in delete_at_index
    del self.timeseries[idx]
TypeError: list indices must be integers or slices, not float
```
## Steps to Reproduce the Problem

    1. Download `Test_belt_pulse_multifreq.txt`
    2. `phys2bids -in Test_belt_pulse_multifreq.txt -chtrig 3 `

## Specifications

    - Python version: 
    - phys2bids version:
    - Platform:

## Possible solution
We need to adress line 305 of code

**Comment by vinferrer** [comment]
I am on it
